---
name: assign
on:
  pull_request: # For testing changes in branch
  # pull_request_target:
  #types: [opened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  assign:
    name: assign
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write
      actions: read
      checks: read
      contents: read
      deployments: read
      #id-token: read
      issues: read
      discussions: read
      packages: read
      pages: read
      repository-projects: read
      security-events: read
      statuses: read
    steps:
      - uses: kentaro-m/auto-assign-action@60730395fd3afb76c7407e16cd4b144fbbcf28a6 # renovate: tag=v1
        with:
          configuration-path: .github/auto-assign.yml # Only needed if you use something other than .github/auto_assign.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
