---
name: release
on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      # https://github.com/magnetikonline/action-golang-cache
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@09043845c4b214830a4ae9eb6f5c61d3d3fd37b0 # renovate: tag=v3
        with:
          go-version-file: go.mod

      - uses: aquaproj/aqua-installer@31c7ddc84bbb8b3b6eff822f03f544192c359bba # renovate: tag=v1.1.2
        with:
          aqua_version: v1.20.2
          # install_path: /tmp/bin/aqua
          # working_directory:
          # aqua_opts: ''
        env:
          AQUA_CONFIG: aqua.ci.yaml
          AQUA_LOG_LEVEL: debug

      - name: mage-init
        run: |
          mage init
      - name: docker-login
        uses: docker/login-action@v2 # renovate: tag=v2
        with:
          username: ${{ secrets.DSV_DOCKER_USERNAME }}
          password: ${{ secrets.DSV_DOCKER_PASSWORD }}
      - name: mage-release
        run: |
          mage release
        env:
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
          DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}
