---
name: test
on:
  pull_request:
  # push:
  # branches:
  #   - main
  # tags:
  #   - v*
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  AQUA_LOG_LEVEL: debug
  AQUA_OPTS: ''
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: env-config
        run: |
          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
      # - name: aqua-install
      #   run: |
      #     # curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash
      #     go run github.com/aquaproj/aqua-installer@latest
      #     aqua install
      #   # echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
      #   env:
      #     AQUA_CONFIG: aqua.ci.yaml
      #     AQUA_LOG_LEVEL: debug
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.20.2
          enable_aqua_install: true
        env:
          AQUA_CONFIG: aqua.ci.yaml
          AQUA_LOG_LEVEL: debug
          AQUA_OPTS: ''

      # - name: aqua-install
      #   run: |
      #     curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash
      #     aqua install
      #   # echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
      #   env:
      #     AQUA_CONFIG: aqua.ci.yaml
      #     AQUA_LOG_LEVEL: debug
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ${HOME}/.cache/go-build
            ${HOME}/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: mage-init
        run: |
          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:${PATH}"
          mage init

      - name: mage-gotestsum
        run: |
          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:${PATH}"
          mage go:testsum ./...
        env:
          # Race conditions will be hit due to the cli driven tasks and binaries being called.
          GOTEST_DISABLE_RACE: 1
